# Tên ứng dụng
spring.application.name=flashcard_ai
# Cấu hình Port cho ứng dụng Web
server.port=8080

# Đường dẫn trỏ tới file JSON chứa khóa bảo mật Firebase Admin SDK
firebase.config-path=classpath:firebase-service-account.json

# Tắt cache Thymeleaf để sửa HTML ăn ngay lập tức không bị delay
spring.thymeleaf.cache=false

# Bật tự động reload tài nguyên tĩnh (nếu dùng DevTools)
spring.devtools.restart.enabled=true

# Danh sách các API Key của AI (có thể thêm nhiều key cách nhau bằng dấu phẩy)
ai.api.keys=AIzaSy_Key_1_Placeholder,AIzaSy_Key_2_Placeholder,AIzaSy_Key_3_Placeholder

